version: "3"

services:
  app:
    image: ghcr.io/mhdramadhanarvin/laravel-autodeploy:${VERSION}
    depends_on:
      - mysql
    networks:
        - network

  webserver:
    image: nginx:alpine-slim
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deploy/docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - mysql
    networks:
      - network

  mysql:
    image: 'mysql:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'mysql:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    networks:
        - network

volumes:
    mysql:
        driver: local

networks:
  network:
