name: Laravel Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Job for running test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test

  terraformCheck:
    name: Job for ensure changes in terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deploy/infrastructure/terraform
    steps:
    - uses: actions/checkout@v3
    - name: Copy the Public key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/laravel-autodeploy
        echo "${{ secrets.PUBLIC_KEY }}" > ~/.ssh/laravel-autodeploy.pub

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-3"

    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
