name: Laravel Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not found

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/php-apache/Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ steps.tag.outputs.tag }}
